version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    environment:
      - FLASK_APP=app.py  # The name of your Flask app
      - FLASK_ENV=development  # Optional, use 'production' in production
    ports:
      - "5000:5000"  # Expose port 5000 for the Flask app
